### ISSUE TITLE
Potential security issue

### ISSUE THREAD

**Issue by JamieSlome** [misterfresh/react-drive-cms#11]
Hey there!

I belong to an open source security research community, and a member (@wjddnjs33) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by misterfresh** [comment]
Just let me know what the issue is. Regards

**Comment by JamieSlome** [comment]
@misterfresh - you can view the report here:

https://huntr.dev/bounties/c773a6b5-d615-4f25-8a96-157aa52747d2/

**Comment by misterfresh** [comment]
It is necessary to use this feature in this case in order to keep the html from google docs. So in the foreseeable future it will stay like this.
