### ISSUE TITLE
How to run this project?

### ISSUE THREAD

**Issue by pacozaa** [misterfresh/react-drive-cms#3]
Hi :)
Would you mind explain how to run this project?

Is it `npm install`  then `gulp` ?

**Comment by misterfresh** [comment]
Try that and let it me know how it goes ;)

**Comment by pacozaa** [comment]
There you go 👍 

![capture](https://cloud.githubusercontent.com/assets/3154089/23458647/b197a106-feaf-11e6-9f10-566a18c5f567.JPG)
![crearac2](https://cloud.githubusercontent.com/assets/3154089/23458653/b6a4fd24-feaf-11e6-98cf-78bc2b6d4e54.JPG)

**Comment by misterfresh** [comment]
Do you have a google drive folder set up like this : https://drive.google.com/drive/folders/0B0A_zASTMp9WU0NMYW9wXzVQWjg

**Comment by pacozaa** [comment]
Thank you for your response.


Yes, I do.

https://drive.google.com/drive/folders/0B_BdCVFaw3DLLXV3dU50UlJnS0k?usp=sharing

**Comment by misterfresh** [comment]
Now it is npm install and npm run dev.
