### ISSUE TITLE
Recommendations to add to instructions

### ISSUE THREAD

**Issue by jannncodes** [misterfresh/react-drive-cms#5]
I found I had to do two extra steps in the Dashboard sheet that would be useful to add into the readme:
-Change the projectFolderName on line 9 in the Dashboard Script to the name of my drive folder
-Publish the Dashboard sheet to the web via File>Publish to the Web...

Thanks for your hard work on this repo!

**Comment by misterfresh** [comment]
Thanks!

**Comment by misterfresh** [comment]
Updated instructions.
