### ISSUE TITLE
Contact form

### ISSUE THREAD

**Issue by mrbilal4972** [misterfresh/react-drive-cms#9]
Can you please explain the process of Contact form that how data is going to save in google drive  in visitor spreadsheet

**Comment by misterfresh** [comment]
In order for the contact form to work, publish the following script as a Google Web App: https://gist.github.com/misterfresh/b69d29a97cf415980be2 . In your "Visitors" Google spreadsheet, go to Tools>Script Editor. You can create a free SendGrid account and paste your SendGrid API key in the script. Save the script and click on Publish>Deploy as Web App.
You also need to configure a verified sender in sendgrid. It can be done with a free account. Then you need to set the verified sender email and name in the "from" and "replyTo" fields in the script https://gist.github.com/misterfresh/b69d29a97cf415980be2 at lines 55 and 59.
